#!/bin/bash
prefixSudo=''
echo "---- Installation de Portainer ---"
${prefixSudo} docker volume create portainer_data
${prefixSudo} docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --label name=portainer --name portainer --restart always portainer/portainer
